### ISSUE TITLE
Enable the jvm plugin

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-java#5]
We should enable the jvm plugin in hawtio-java - its currently hidden, and you have to use /jvm to access it

**Comment by gashcrumb** [comment]
Yeah, we disable that for kubernetes in fabric8-console, guess we need a way to selectively do that somehow.  Maybe it's time to introduce a general config.json or config.js that we can use server-side to control what's available in the UI, and to give plugins a nice easy way to configure themselves without having to resort to a lot of troublesome discovery and so on.

**Comment by gashcrumb** [comment]
Another option which might be better anyway is to have an assembly specific to hawtio-java.  Then we can also pull in some of the other plugins like tomcat/jboss etc.

**Comment by gashcrumb** [comment]
Switched to [this](https://github.com/hawtio/hawtio-java/tree/master/hawtio-console-assembly) which doesn't disable the JVM plugin.
